Connected to Python 3.11.5

In [1]:
import pandas as pd

df = pd.read_csv('data.csv')
df = df.drop(df.columns[df.columns.str.contains('Unnamed')], axis=1)
op = dict(df['Play Golf'].value_counts())
rows = df.shape[0]

In [2]:
def find_probs(out_label):
    prob = {}
    for column in df.columns[:-1]:
        column_d = {}
        for class_ in df[column].unique():
            t_d = {}
            for output in df[out_label].unique():
                occurrences = ((df[column] == class_) & (df[out_label] == output)).sum()
                t_d[output] = occurrences/op[output]
            prob[str(class_)] = t_d
    prob_df = pd.DataFrame(prob)
    return prob_df

In [3]:
def predict(X,prob_df):
    p_yes = op['Yes']/rows
    p_no = op['No']/rows
    for attr in X:
        p_yes *= prob_df[attr]['Yes']
        p_no *= prob_df[attr]['No']
    P_yes = round(p_yes/(p_yes+p_no),2)
    P_no = round(p_no/(p_yes+p_no),2)
    return "Yes" if P_yes >= P_no else "No"

In [4]:
prob_df = find_probs('Play Golf')
predict(['Rainy','Cool','Normal','False'],prob_df)

'Yes'

In [5]:
def accuracy():
    count = 0
    for index,row in df.iterrows():
        r = list(map(str,row))
        if predict(r[:-1]) == r[-1]:
            count += 1
        
    print(count)

In [6]:
df

     Outlook  Temp Humidity  Windy Play Golf
0      Rainy   Hot     High  False        No
1      Rainy   Hot     High   True        No
2   Overcast   Hot     High  False       Yes
3      Sunny  Mild     High  False       Yes
4      Sunny  Cool   Normal  False       Yes
5      Sunny  Cool   Normal   True        No
6   Overcast  Cool   Normal   True       Yes
7   Overcast  Mild     High  False        No
8      Sunny  Cool   Normal  False       Yes
9      Rainy  Mild   Normal  False       Yes
10     Sunny  Mild   Normal   True       Yes
11     Rainy  Mild     High   True       Yes
12     Rainy   Hot   Normal  False       Yes
13     Sunny  Mild     High   True        No
14     Sunny  Cool   Normal  False       Yes
15     Sunny  Mild     High   True       Yes
16  Overcast   Hot     High  False       Yes
17  Overcast   Hot   Normal   True       Yes
18     Sunny  Mild   Normal  False        No
19     Rainy  Cool   Normal   True       Yes